spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB   #单个文件的最大上限
      max-request-size: 3MB #单个请求的文件总大小上限
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC #修改ip以及端口 和密码
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    deserialization.UNWRAP_ROOT_VALUE: true
  redis:
    host: localhost  #修改端口
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
  data:
    mongodb:
      uri: mongodb://localhost/blog
  elasticsearch:
    username: elastic
    password: 123456
    uris: http://localhost:9200


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: dao/*.xml
image:
  default: https://static.productionready.io/images/smiley-cyrus.jpg
jwt:
  secret: nRvyYC4soFxBdZ-F-5Nnzz5USXstR1YylsTd-mA0aKtI9HUlriGrtkf-TiuDapkLiUCogO3JOK7kwZisrHp6wA
  sessionTime: 86400

  #修改文件上传和读取地址
web:
  upload-path: D:\learn_software\program_file\IDEAProgject\personal_blog\src\main\resources\static\img\
  realpath: D:/learn_software/program_file/IDEAProgject/personal_blog/src/main/resources/static/


mail:
  # 配置 SMTP 服务器地址
  host: smtp.163.com
  # 发送者邮箱
  username: fischer0522@163.com
  # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
  password: FLFCRBRSZUBWSLYB
  # 端口号163默认为 465 994
  port: 465
  # 默认的邮件编码为UTF-8


# es的uri
es:
  host: http://localhost:9200



